109

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -40,7 +40,7 @@ jobs:
             --region ${{ env.REGION }} --format='value(endpoint)')
           CA_CERT=$(gcloud container clusters describe ${{ env.CLUSTER_NAME }} \
             --region ${{ env.REGION }} --format='value(masterAuth.clusterCaCertificate)')
-          cat <<EOF > $HOME/.kube/config
+          cat << 'EOF' > $HOME/.kube/config
           apiVersion: v1
           kind: Config
           clusters:
@@ -59,6 +59,14 @@ jobs:
               user: gke-user
           current-context: gke-context
           EOF
+
+      - name: Show kubeconfig raw file
+        run: |
+          echo "==============="
+          echo "KUBECONFIG RAW"
+          echo "==============="
+          cat $HOME/.kube/config || echo "(FILE NOT FOUND)"
+          echo "---------------"
 
       - name: Debug kubeconfig
         run: cat $HOME/.kube/config
